# Generated by Django 3.1.2 on 2020-10-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
